### ISSUE TITLE
Error about data preprocess

### ISSUE THREAD

**Issue by TuoCai2000** [KChen-lab/Monopogen#13]
Hello!Thank you for developing monopogen!
I run the code:**python  ${path}/src/Monopogen.py  preProcess -b test.lst -o 01.test  -a ${path}/apps**,but got error like this:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/public/home/user/program/miniconda3/envs/monopogen/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/public/home/user/program/miniconda3/envs/monopogen/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/public/home/user/program/Monopogen/src/germline.py", line 206, in BamFilter
    if val < max_mismatch:
UnboundLocalError: local variable 'val' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/user/program/Monopogen/src/Monopogen.py", line 435, in <module>
    main()
  File "/public/home/user/program/Monopogen/src/Monopogen.py", line 428, in main
    args.func(args)
  File "/public/home/user/program/Monopogen/src/Monopogen.py", line 313, in preProcess
    result = pool.map(BamFilter, para_lst)
  File "/public/home/user/program/miniconda3/envs/monopogen/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/public/home/user/program/miniconda3/envs/monopogen/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
UnboundLocalError: local variable 'val' referenced before assignment

I would appreciate if you can help me.
Thank you very much!

**Comment by jinzhuangdou** [comment]
Hi, could you check whether "NM" or "nM" tag available in your bam files?

**Comment by TuoCai2000** [comment]
Yes，I checked my bam files and found NM tag available. How can I process it to apply Monopogen into my bam files? Thank you so much!!

**Comment by TuoCai2000** [comment]
Hi ,thank you for quickly answering my question!
 I just found my bam files sorted by the chromsome:chr1,chr2...chrX,chrY,chrM,GL000008.2...
 And if I run the code ,I can get the output like this even if it errors:
 ---------------------------------------------------------------------------
total 361052
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr10.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr11.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr12.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr13.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr14.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr15.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr16.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr17.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr18.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr19.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr1.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr20.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr21.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        41 Sep  6 18:34 chr22.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr2.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr3.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr4.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr5.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr6.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr7.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr8.filter.bam.lst
-rw-r--r-- 1 caituo zhulab        40 Sep  6 18:34 chr9.filter.bam.lst
-rw-r--r-- 1 caituo zhulab   5875414 Sep  6 18:46 LGDR1-10_chr10.filter.bam
-rw-r--r-- 1 caituo zhulab     87752 Sep  6 18:46 LGDR1-10_chr10.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  21532825 Sep  6 18:46 LGDR1-10_chr11.filter.bam
-rw-r--r-- 1 caituo zhulab     90712 Sep  6 18:46 LGDR1-10_chr11.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  12284703 Sep  6 18:47 LGDR1-10_chr12.filter.bam
-rw-r--r-- 1 caituo zhulab     88984 Sep  6 18:47 LGDR1-10_chr12.filter.bam.bai
-rw-r--r-- 1 caituo zhulab   5181496 Sep  6 18:46 LGDR1-10_chr13.filter.bam
-rw-r--r-- 1 caituo zhulab     70912 Sep  6 18:46 LGDR1-10_chr13.filter.bam.bai
-rw-r--r-- 1 caituo zhulab   3862777 Sep  6 18:46 LGDR1-10_chr14.filter.bam
-rw-r--r-- 1 caituo zhulab     68344 Sep  6 18:46 LGDR1-10_chr14.filter.bam.bai
-rw-r--r-- 1 caituo zhulab      7412 Sep  6 18:46 LGDR1-10_chr15.filter.bam
-rw-r--r-- 1 caituo zhulab      4456 Sep  6 18:34 LGDR1-10_chr15.filter.bam.bai
-rw-r--r-- 1 caituo zhulab      7426 Sep  6 18:34 LGDR1-10_chr16.filter.bam
-rw-r--r-- 1 caituo zhulab      4456 Sep  6 18:34 LGDR1-10_chr16.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  13331062 Sep  6 18:46 LGDR1-10_chr17.filter.bam
-rw-r--r-- 1 caituo zhulab     62200 Sep  6 18:46 LGDR1-10_chr17.filter.bam.bai
-rw-r--r-- 1 caituo zhulab   2809370 Sep  6 18:46 LGDR1-10_chr18.filter.bam
-rw-r--r-- 1 caituo zhulab     51400 Sep  6 18:46 LGDR1-10_chr18.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  19726554 Sep  6 18:46 LGDR1-10_chr19.filter.bam
-rw-r--r-- 1 caituo zhulab     48728 Sep  6 18:46 LGDR1-10_chr19.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  24781345 Sep  6 18:46 LGDR1-10_chr1.filter.bam
-rw-r--r-- 1 caituo zhulab    161440 Sep  6 18:46 LGDR1-10_chr1.filter.bam.bai
-rw-r--r-- 1 caituo zhulab   5866005 Sep  6 18:47 LGDR1-10_chr20.filter.bam
-rw-r--r-- 1 caituo zhulab     45016 Sep  6 18:47 LGDR1-10_chr20.filter.bam.bai
-rw-r--r-- 1 caituo zhulab 178118080 Sep  6 18:47 LGDR1-10_chr21.filter.bam
-rw-r--r-- 1 caituo zhulab     70712 Sep  6 18:47 LGDR1-10_chr21.filter.bam.bai
-rw-r--r-- 1 caituo zhulab   4883524 Sep  6 18:47 LGDR1-10_chr22.filter.bam
-rw-r--r-- 1 caituo zhulab     37136 Sep  6 18:47 LGDR1-10_chr22.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  15516960 Sep  6 18:46 LGDR1-10_chr2.filter.bam
-rw-r--r-- 1 caituo zhulab    151872 Sep  6 18:46 LGDR1-10_chr2.filter.bam.bai
-rw-r--r-- 1 caituo zhulab      7412 Sep  6 18:46 LGDR1-10_chr3.filter.bam
-rw-r--r-- 1 caituo zhulab      4456 Sep  6 18:34 LGDR1-10_chr3.filter.bam.bai
-rw-r--r-- 1 caituo zhulab      7426 Sep  6 18:34 LGDR1-10_chr4.filter.bam
-rw-r--r-- 1 caituo zhulab      4456 Sep  6 18:34 LGDR1-10_chr4.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  15036108 Sep  6 18:46 LGDR1-10_chr5.filter.bam
-rw-r--r-- 1 caituo zhulab    117640 Sep  6 18:46 LGDR1-10_chr5.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  10952824 Sep  6 18:46 LGDR1-10_chr6.filter.bam
-rw-r--r-- 1 caituo zhulab    109880 Sep  6 18:46 LGDR1-10_chr6.filter.bam.bai
-rw-r--r-- 1 caituo zhulab  14526624 Sep  6 18:46 LGDR1-10_chr7.filter.bam
-rw-r--r-- 1 caituo zhulab    103976 Sep  6 18:46 LGDR1-10_chr7.filter.bam.bai
-rw-r--r-- 1 caituo zhulab   6764889 Sep  6 18:46 LGDR1-10_chr8.filter.bam
-rw-r--r-- 1 caituo zhulab     92160 Sep  6 18:46 LGDR1-10_chr8.filter.bam.bai
-rw-r--r-- 1 caituo zhulab   6879066 Sep  6 18:46 LGDR1-10_chr9.filter.bam
-rw-r--r-- 1 caituo zhulab     88448 Sep  6 18:46 LGDR1-10_chr9.filter.bam.bai
-----------------------------------------------------------------------------------------------
So I wonder if such error is fine for me ? I persume I would only come up with this error when it processed to the chromsome like chrX,chrY,chrM,GL000008.2...So even with this error,I can still get my result,and it looks fine. I wonder if I comprehend it in the right way?

**Comment by jinzhuangdou** [comment]
We have not tested monopogen on sex chromosomes. They have different imputation mode from reference panel. The preprocess step should be okay if you can generate the filtered bam files.

**Comment by zheng-sc** [comment]
Hey , I met the same error.

> [2023-09-14 10:54:04,148] INFO     Monopogen.py Performing data preprocess before variant calling...
> [2023-09-14 10:54:04,148] INFO     germline.py Parameters in effect:
> [2023-09-14 10:54:04,148] INFO     germline.py --subcommand = [preProcess]
> [2023-09-14 10:54:04,148] INFO     germline.py --bamFile = [bam_S7.lst]
> [2023-09-14 10:54:04,148] INFO     germline.py --out = [S7_out]
> [2023-09-14 10:54:04,148] INFO     germline.py --app_path = [/home/big/zheng/Monopogen/apps]
> [2023-09-14 10:54:04,148] INFO     germline.py --max_mismatch = [3]
> [2023-09-14 10:54:04,148] INFO     germline.py --nthreads = [16]
> [2023-09-14 10:54:04,165] DEBUG    Monopogen.py PreProcessing sample S7
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/zheng/anaconda3/envs/monopogen/lib/python3.8/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/zheng/anaconda3/envs/monopogen/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
>     return list(map(*args))
>   File "/home/big/zheng/Monopogen/src/germline.py", line 206, in BamFilter
>     if val < max_mismatch:
> UnboundLocalError: local variable 'val' referenced before assignment
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/big/zheng/Monopogen/src/Monopogen.py", line 435, in <module>
>     main()
>   File "/home/big/zheng/Monopogen/src/Monopogen.py", line 428, in main
>     args.func(args)
>   File "/home/big/zheng/Monopogen/src/Monopogen.py", line 313, in preProcess
>     result = pool.map(BamFilter, para_lst)
>   File "/home/zheng/anaconda3/envs/monopogen/lib/python3.8/multiprocessing/pool.py", line 364, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/home/zheng/anaconda3/envs/monopogen/lib/python3.8/multiprocessing/pool.py", line 771, in get
>     raise self._value
> UnboundLocalError: local variable 'val' referenced before assignment

**I checked the 'NM' tag in the bam file using the command `samtools view S7_final.bam` and the result shows**

> A00627:649:HFLL7DSX7:4:1443:26775:28917 165     chr1    10015   0       *       =       10015   0       ATTTATCTATGTACGCAAGTGGCCGATCATTCGCATCGGCGTACGACTTCTTCACAATCCACGTGCTTGAGACTGTGGTGGTATAC  :FFFFFFFFFFFFFFFFF:F:FFFFF:::,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFF:FFFFFFFFFFF       rl:i:0  MQ:i:0  MC:Z:14S92M1I43M        ms:i:4140
> A00627:649:HFLL7DSX7:4:1443:26775:28917 89      chr1    10015   0       14S92M1I43M     =       10015   0       TTAACATTACACTTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCC       F,FF::FFF,,,F,FF:,F,:,,,FF,:F:F,F,F:F,F,:FFFF:,,F:F,,,FFF,F,FFF:,,FFF:::F,FFFFF:F:FFFF:,:FFFF,:F:FF:FFFF:F,,F,FFFFFF:FFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFF  NM:i:2  AS:i:246        nn:i:0  tp:A:P  cm:i:16 s1:i:123     s2:i:123        de:f:0.0147     rl:i:0  MC:Z:*  ms:i:3024
> A00627:649:HFLL7DSX7:4:1356:25446:20979 2121    chr1    10036   0       65H51M34H       =       10036   0       CTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA     FFF:FFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFF:FFF     NM:i:0  ms:i:102     AS:i:102        nn:i:0  tp:A:P  cm:i:5  s1:i:45 s2:i:45 de:f:0  SA:Z:chr5,83515783,+,71M79S,60,0;       rl:i:0
> A00627:649:HFLL7DSX7:4:1663:14434:25958 65      chr1    10053   14      56M1I23M70S     chr12   54151866        0       CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAAACCCAAACCCTAACCCTAACCCAAAACCAAACCCAAACCCAAAACCAAACCCAAACCCAAACCCAAACCCAAACCCAAACCCAAAACAACCC       FF,FFFFF:FF:FFFFFFFF,FFFFF,FF:FF:FFFFF,FFFFF,FF:FF,FF:FF,FFFFF,FFFFF,FF,FF,FFFFF,FF,FF:F:,FF,FF,FF,FF,FF,FFFFF,FFFF::F:,FF,FF:FF,FF,:F,:F,FF,F:FF,F,:F  NM:i:2  AS:i:134        nn:i:0  tp:A:P  cm:i:7       s1:i:54 s2:i:54 de:f:0.025      SA:Z:chr13,106450659,+,102S37M11S,10,0; rl:i:0  MQ:i:23 MC:Z:30S56M     ms:i:2418
> A00627:649:HFLL7DSX7:4:1511:12644:13150 163     chr1    10059   0       55S31M  =       10156   181     CAAGCACGTGGATTACTTCGTAGTCGTACCCCGATGCTAAACATCGGCCACTCATCCTAACCCTAACCCTAACCCTAACCCTAACC  FFFFFFFFFFFFFFFFFF,:,,F,F:,,,,FFFFFF,F,,FFFFF:FFF:FFFFFFFFFFF,,:FFFFFFF:FFFFFFFFFFFFFF       NM:i:0  AS:i:62 nn:i:0  tp:A:P  cm:i:1  s1:i:92 s2:i:91 de:f:0  rl:i:0  MQ:i:0  MC:Z:66S22M1I53M1D8M    ms:i:3605
> A00627:649:HFLL7DSX7:4:1129:3341:16172  165     chr1    10061   0       *       =       10061   0       GTCTGTCTTTACAGCAGAGTGGCCGATGTTTCGCATCGGCGTACGACTAGCACCTCATCCACGTGCTTGAGACTGTGGACTATTGC  FFFFFFFFFFFFFFF:FFF,F:,FFF:::,F,FF,FFF:FF,,FFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       rl:i:0  MQ:i:39 MC:Z:5S46M1I48M5D14M4D36M       ms:i:4078
> A00627:649:HFLL7DSX7:4:1129:3341:16172  89      chr1    10061   39      5S46M1I48M5D14M4D36M    =       10061   0       AAACATAACCCTAACCCTAACCCTAACCATAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC       ,F,:,:FF,FFFFF,:FFFF,::FF,F,,F:FF,,:F:,,:FFF,F,:FFF,,F:,FF,FF,,F,::,F,FF:FFF:,FF:,FFF:::,,:F,FFF:,FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:,FFFF,:F  NM:i:12 AS:i:212        nn:i:0  tp:A:P  cm:i:9       s1:i:95 s2:i:100        de:f:0.034      rl:i:0  MC:Z:*  ms:i:2839
> A00627:649:HFLL7DSX7:4:1155:3974:23594  165     chr1    10068   0       *       =       10068   0       GGAATTAGCTGACAGTGCGTGGCCGATGTTTCGCATCGGCGTACGACTGACAGTGCATCCACGTGCTTGAGACTGTGGTCTGATCC  FFF:FFFFFFFFFFFFFFF:FF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       rl:i:0  MQ:i:60 MC:Z:39M1I40M1D18M1I4M1I6M4D40M ms:i:4128
> A00627:649:HFLL7DSX7:4:1155:3974:23594  89      chr1    10068   60      39M1I40M1D18M1I4M1I6M4D40M      =       10068   0       AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACACTAATCCCTAAACCCTTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC       :,,F,F::,:FFFF:::FFF,:,F:F,,FFF:,:FFFF,,FF:,:,FF:F::FFFF,:FFF::,FFF,,,FFFF:,FFF:,FFFFF,,FFF,,,,:,:,:FF:F,FFFFF,FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  NM:i:11 AS:i:188        nn:i:0  tp:A:P       cm:i:10 s1:i:97 s2:i:96 de:f:0.0526     rl:i:0  MC:Z:*  ms:i:3121
> A00627:649:HFLL7DSX7:4:1362:9362:5869   65      chr1    10092   1       17M1I38M1D30M1I44M19S   chr20   64287018        0       AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAAACCCTAACCCTAACCCTAACCCTAACCCAAACCCTAACCCAAACCCTAACCCTAACCCTAACCCTAACCCGGGCGCTAAGCCTGGCCCG       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF,,FFF:F,:FFFF,FFF:F:FF:F,::FF::,FFFFF,:F,F:,::,,:,,F,F:,,,,::,:,,,,,,:,:F,,,,,,,,,,,,,,,,,,,  NM:i:6  AS:i:186        nn:i:0  tp:A:P       cm:i:2  s1:i:42 s2:i:50 de:f:0.0455     rl:i:114        MQ:i:7  MC:Z:4M1D52M30S ms:i:2075

**seems only some of the sequences are tagged with "NM".** 

**And when I run Mnopogen preprocess, I can only get the following outputs:**
S7_chr10.filter.bam      S7_chr13.filter.bam      S7_chr15.filter.bam.bai  S7_chr17.filter.bam.bai  S7_chr1.filter.bam       S7_chr22.filter.bam      S7_chr3.filter.bam      S7_chr5.filter.bam      S7_chr7.filter.bam
S7_chr10.filter.bam.bai  S7_chr13.filter.bam.bai  S7_chr16.filter.bam      S7_chr18.filter.bam      S7_chr20.filter.bam      S7_chr22.filter.bam.bai  S7_chr3.filter.bam.bai  S7_chr5.filter.bam.bai  S7_chr7.filter.bam.bai
S7_chr11.filter.bam      S7_chr14.filter.bam      S7_chr16.filter.bam.bai  S7_chr18.filter.bam.bai  S7_chr21.filter.bam      S7_chr2.filter.bam       S7_chr4.filter.bam      S7_chr6.filter.bam      S7_chr8.filter.bam
S7_chr12.filter.bam      S7_chr15.filter.bam      S7_chr17.filter.bam      S7_chr19.filter.bam      S7_chr21.filter.bam.bai  S7_chr2.filter.bam.bai   S7_chr4.filter.bam.bai  S7_chr6.filter.bam.bai  S7_chr9.filter.bam

**some of them missed .bai and without .filter.bam.lst files.**

**could you please tell me how to solve this problem?**

**Comment by zheng-sc** [comment]
> Hey , I met the same error.
> 
> > [2023-09-14 10:54:04,148] INFO     Monopogen.py Performing data preprocess before variant calling...
> > [2023-09-14 10:54:04,148] INFO     germline.py Parameters in effect:
> > [2023-09-14 10:54:04,148] INFO     germline.py --subcommand = [preProcess]
> > [2023-09-14 10:54:04,148] INFO     germline.py --bamFile = [bam_S7.lst]
> > [2023-09-14 10:54:04,148] INFO     germline.py --out = [S7_out]
> > [2023-09-14 10:54:04,148] INFO     germline.py --app_path = [/home/big/zheng/Monopogen/apps]
> > [2023-09-14 10:54:04,148] INFO     germline.py --max_mismatch = [3]
> > [2023-09-14 10:54:04,148] INFO     germline.py --nthreads = [16]
> > [2023-09-14 10:54:04,165] DEBUG    Monopogen.py PreProcessing sample S7
> > multiprocessing.pool.RemoteTraceback:
> > """
> > Traceback (most recent call last):
> > File "/home/zheng/anaconda3/envs/monopogen/lib/python3.8/multiprocessing/pool.py", line 125, in worker
> > result = (True, func(*args, **kwds))
> > File "/home/zheng/anaconda3/envs/monopogen/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
> > return list(map(*args))
> > File "/home/big/zheng/Monopogen/src/germline.py", line 206, in BamFilter
> > if val < max_mismatch:
> > UnboundLocalError: local variable 'val' referenced before assignment
> > """
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "/home/big/zheng/Monopogen/src/Monopogen.py", line 435, in 
> > main()
> > File "/home/big/zheng/Monopogen/src/Monopogen.py", line 428, in main
> > args.func(args)
> > File "/home/big/zheng/Monopogen/src/Monopogen.py", line 313, in preProcess
> > result = pool.map(BamFilter, para_lst)
> > File "/home/zheng/anaconda3/envs/monopogen/lib/python3.8/multiprocessing/pool.py", line 364, in map
> > return self._map_async(func, iterable, mapstar, chunksize).get()
> > File "/home/zheng/anaconda3/envs/monopogen/lib/python3.8/multiprocessing/pool.py", line 771, in get
> > raise self._value
> > UnboundLocalError: local variable 'val' referenced before assignment
> 
> **I checked the 'NM' tag in the bam file using the command `samtools view S7_final.bam` and the result shows**
> 
> > A00627:649:HFLL7DSX7:4:1443:26775:28917 165     chr1    10015   0       *       =       10015   0       ATTTATCTATGTACGCAAGTGGCCGATCATTCGCATCGGCGTACGACTTCTTCACAATCCACGTGCTTGAGACTGTGGTGGTATAC  :FFFFFFFFFFFFFFFFF:F:FFFFF:::,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFF:FFFFFFFFFFF       rl:i:0  MQ:i:0  MC:Z:14S92M1I43M        ms:i:4140
> > A00627:649:HFLL7DSX7:4:1443:26775:28917 89      chr1    10015   0       14S92M1I43M     =       10015   0       TTAACATTACACTTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCC       F,FF::FFF,,,F,FF:,F,:,,,FF,:F:F,F,F:F,F,:FFFF:,,F:F,,,FFF,F,FFF:,,FFF:::F,FFFFF:F:FFFF:,:FFFF,:F:FF:FFFF:F,,F,FFFFFF:FFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFF  NM:i:2  AS:i:246        nn:i:0  tp:A:P  cm:i:16 s1:i:123     s2:i:123        de:f:0.0147     rl:i:0  MC:Z:*  ms:i:3024
> > A00627:649:HFLL7DSX7:4:1356:25446:20979 2121    chr1    10036   0       65H51M34H       =       10036   0       CTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA     FFF:FFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFF:FFF     NM:i:0  ms:i:102     AS:i:102        nn:i:0  tp:A:P  cm:i:5  s1:i:45 s2:i:45 de:f:0  SA:Z:chr5,83515783,+,71M79S,60,0;       rl:i:0
> > A00627:649:HFLL7DSX7:4:1663:14434:25958 65      chr1    10053   14      56M1I23M70S     chr12   54151866        0       CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAAACCCAAACCCTAACCCTAACCCAAAACCAAACCCAAACCCAAAACCAAACCCAAACCCAAACCCAAACCCAAACCCAAACCCAAAACAACCC       FF,FFFFF:FF:FFFFFFFF,FFFFF,FF:FF:FFFFF,FFFFF,FF:FF,FF:FF,FFFFF,FFFFF,FF,FF,FFFFF,FF,FF:F:,FF,FF,FF,FF,FF,FFFFF,FFFF::F:,FF,FF:FF,FF,:F,:F,FF,F:FF,F,:F  NM:i:2  AS:i:134        nn:i:0  tp:A:P  cm:i:7       s1:i:54 s2:i:54 de:f:0.025      SA:Z:chr13,106450659,+,102S37M11S,10,0; rl:i:0  MQ:i:23 MC:Z:30S56M     ms:i:2418
> > A00627:649:HFLL7DSX7:4:1511:12644:13150 163     chr1    10059   0       55S31M  =       10156   181     CAAGCACGTGGATTACTTCGTAGTCGTACCCCGATGCTAAACATCGGCCACTCATCCTAACCCTAACCCTAACCCTAACCCTAACC  FFFFFFFFFFFFFFFFFF,:,,F,F:,,,,FFFFFF,F,,FFFFF:FFF:FFFFFFFFFFF,,:FFFFFFF:FFFFFFFFFFFFFF       NM:i:0  AS:i:62 nn:i:0  tp:A:P  cm:i:1  s1:i:92 s2:i:91 de:f:0  rl:i:0  MQ:i:0  MC:Z:66S22M1I53M1D8M    ms:i:3605
> > A00627:649:HFLL7DSX7:4:1129:3341:16172  165     chr1    10061   0       *       =       10061   0       GTCTGTCTTTACAGCAGAGTGGCCGATGTTTCGCATCGGCGTACGACTAGCACCTCATCCACGTGCTTGAGACTGTGGACTATTGC  FFFFFFFFFFFFFFF:FFF,F:,FFF:::,F,FF,FFF:FF,,FFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       rl:i:0  MQ:i:39 MC:Z:5S46M1I48M5D14M4D36M       ms:i:4078
> > A00627:649:HFLL7DSX7:4:1129:3341:16172  89      chr1    10061   39      5S46M1I48M5D14M4D36M    =       10061   0       AAACATAACCCTAACCCTAACCCTAACCATAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC       ,F,:,:FF,FFFFF,:FFFF,::FF,F,,F:FF,,:F:,,:FFF,F,:FFF,,F:,FF,FF,,F,::,F,FF:FFF:,FF:,FFF:::,,:F,FFF:,FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:,FFFF,:F  NM:i:12 AS:i:212        nn:i:0  tp:A:P  cm:i:9       s1:i:95 s2:i:100        de:f:0.034      rl:i:0  MC:Z:*  ms:i:2839
> > A00627:649:HFLL7DSX7:4:1155:3974:23594  165     chr1    10068   0       *       =       10068   0       GGAATTAGCTGACAGTGCGTGGCCGATGTTTCGCATCGGCGTACGACTGACAGTGCATCCACGTGCTTGAGACTGTGGTCTGATCC  FFF:FFFFFFFFFFFFFFF:FF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       rl:i:0  MQ:i:60 MC:Z:39M1I40M1D18M1I4M1I6M4D40M ms:i:4128
> > A00627:649:HFLL7DSX7:4:1155:3974:23594  89      chr1    10068   60      39M1I40M1D18M1I4M1I6M4D40M      =       10068   0       AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACACTAATCCCTAAACCCTTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC       :,,F,F::,:FFFF:::FFF,:,F:F,,FFF:,:FFFF,,FF:,:,FF:F::FFFF,:FFF::,FFF,,,FFFF:,FFF:,FFFFF,,FFF,,,,:,:,:FF:F,FFFFF,FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  NM:i:11 AS:i:188        nn:i:0  tp:A:P       cm:i:10 s1:i:97 s2:i:96 de:f:0.0526     rl:i:0  MC:Z:*  ms:i:3121
> > A00627:649:HFLL7DSX7:4:1362:9362:5869   65      chr1    10092   1       17M1I38M1D30M1I44M19S   chr20   64287018        0       AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAAACCCTAACCCTAACCCTAACCCTAACCCAAACCCTAACCCAAACCCTAACCCTAACCCTAACCCTAACCCGGGCGCTAAGCCTGGCCCG       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF,,FFF:F,:FFFF,FFF:F:FF:F,::FF::,FFFFF,:F,F:,::,,:,,F,F:,,,,::,:,,,,,,:,:F,,,,,,,,,,,,,,,,,,,  NM:i:6  AS:i:186        nn:i:0  tp:A:P       cm:i:2  s1:i:42 s2:i:50 de:f:0.0455     rl:i:114        MQ:i:7  MC:Z:4M1D52M30S ms:i:2075
> 
> **seems only some of the sequences are tagged with "NM".**
> 
> **And when I run Mnopogen preprocess, I can only get the following outputs:** S7_chr10.filter.bam S7_chr13.filter.bam S7_chr15.filter.bam.bai S7_chr17.filter.bam.bai S7_chr1.filter.bam S7_chr22.filter.bam S7_chr3.filter.bam S7_chr5.filter.bam S7_chr7.filter.bam S7_chr10.filter.bam.bai S7_chr13.filter.bam.bai S7_chr16.filter.bam S7_chr18.filter.bam S7_chr20.filter.bam S7_chr22.filter.bam.bai S7_chr3.filter.bam.bai S7_chr5.filter.bam.bai S7_chr7.filter.bam.bai S7_chr11.filter.bam S7_chr14.filter.bam S7_chr16.filter.bam.bai S7_chr18.filter.bam.bai S7_chr21.filter.bam S7_chr2.filter.bam S7_chr4.filter.bam S7_chr6.filter.bam S7_chr8.filter.bam S7_chr12.filter.bam S7_chr15.filter.bam S7_chr17.filter.bam S7_chr19.filter.bam S7_chr21.filter.bam.bai S7_chr2.filter.bam.bai S7_chr4.filter.bam.bai S7_chr6.filter.bam.bai S7_chr9.filter.bam
> 
> **some of them missed .bai and without .filter.bam.lst files.**
> 
> **could you please tell me how to solve this problem?**

**I think the problem is that I failed to integrate the cell barcode(read1_fq.gz) and the cDNA(read2.fq.gz) may I ask which tool are you using to generate the bam file?.**
