### ISSUE TITLE
Error on gemline calling

### ISSUE THREAD

**Issue by carolwxm** [KChen-lab/Monopogen#26]
Hello,
Thank you for developing such a wonderful tool.
Recently, I attempted to execute somatic variant calling from scRNA-seq data.
The preprocess and germline calling sections executed successfully.  However, I encountered an issue during the first step of somatic calling.
-------------------------------------------------------------------------------------------------------------------------------

My code:
python {path}/Monopogen/src/Monopogen.py somatic \
       -a {path}/Monopogen/apps \
       -r region.lst -t 16 \
       -i {path}/${sample} \
       -l ./cell_barcode_annotations.tsv \
       -s featureInfo \
       -g {path}/GRCh38.fa
-------------------------------------------------------------------------------------------------------------------------------

Error Message:
[2023-10-26 10:05:38,384] INFO     Monopogen.py Get feature information from sequencing data...
[E::hts_open_format] Failed to open file "{output_path}/germline/chr7.phased.vcf.gz" : No such file or directory
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr1.phased.vcf.gz'
[W::vcf_parse] Contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '/{output_path}/germline/chr2.phased.vcf.gz'
[W::vcf_parse] Contig 'chr2' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr4.phased.vcf.gz'
[W::vcf_parse] Contig 'chr4' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr3.phased.vcf.gz'
[W::vcf_parse] Contig 'chr3' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{path}/germline/chr5.phased.vcf.gz'
[W::vcf_parse] Contig 'chr5' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '/{output_path}/germline/chr6.phased.vcf.gz'
[W::vcf_parse] Contig 'chr6' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr8.phased.vcf.gz'
[W::vcf_parse] Contig 'chr8' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr9.phased.vcf.gz'
[W::vcf_parse] Contig 'chr9' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr10.phased.vcf.gz'
[W::vcf_parse] Contig 'chr10' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr11.phased.vcf.gz'
[W::vcf_parse] Contig 'chr11' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr12.phased.vcf.gz'
[W::vcf_parse] Contig 'chr12' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr13.phased.vcf.gz'
[W::vcf_parse] Contig 'chr13' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr14.phased.vcf.gz'
[W::vcf_parse] Contig 'chr14' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr16.phased.vcf.gz'
[W::vcf_parse] Contig 'chr16' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr15.phased.vcf.gz'
[W::vcf_parse] Contig 'chr15' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr2.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr4.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr1.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr5.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr3.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr8.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr6.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr12.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr9.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr10.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr11.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}germline/chr13.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr14.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr17.phased.vcf.gz'
[W::vcf_parse] Contig 'chr17' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr16.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr15.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr17.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr18.phased.vcf.gz'
[W::vcf_parse] Contig 'chr18' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr18.gl.vcf.gz'
[E::hts_open_format] Failed to open file "{output_path}/germline/chr19.phased.vcf.gz" : No such file or directory
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr20.phased.vcf.gz'
[W::vcf_parse] Contig 'chr20' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr20.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr21.phased.vcf.gz'
[W::vcf_parse] Contig 'chr21' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr21.gl.vcf.gz'
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr22.phased.vcf.gz'
[W::vcf_parse] Contig 'chr22' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::idx_find_and_load] Could not retrieve index file for '{output_path}/germline/chr22.gl.vcf.gz'
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "~/miniconda2/envs/Monopogen/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "~/miniconda2/envs/Monopogen/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Monopogen/src/somatic.py", line 88, in featureInfo
    vcf_in = VariantFile(out + "/germline/" +  region + ".phased.vcf.gz")
  File "pysam/libcbcf.pyx", line 4117, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4342, in pysam.libcbcf.VariantFile.open
FileNotFoundError: [Errno 2] could not open variant file `b'{output_path}/germline/chr7.phased.vcf.gz'`: No such file or directory
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Monopogen/src/Monopogen.py", line 435, in <module>
    main()
  File "/Monopogen/src/Monopogen.py", line 428, in main
    args.func(args)
  File "/Monopogen/src/Monopogen.py", line 150, in somatic
    result = pool.map(featureInfo, joblst)
  File "~/miniconda2/envs/Monopogen/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "~/miniconda2/envs/Monopogen/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] could not open variant file `b'{output_path}/germline/chr7.phased.vcf.gz'`: No such file or directory
-------------------------------------------------------------------------------------------------------------------------------
I would be very grateful if you could provide some guidance on how to resolve this issue?

**Comment by jinzhuangdou** [comment]
It seems the germline module is not finished successfully. Are you able to examine whether there are variants called in chr7.phased.vcf.gz?
