### ISSUE TITLE
No sush file: chr20.gp.vcf.gz

### ISSUE THREAD

**Issue by jefferyUstc** [KChen-lab/Monopogen#3]
Script:
```
path=/XXXXXX/Monopogen
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${path}/apps

python  ../src/Monopogen.py    SCvarCall \
      -b  ../example/chr20_2Mb.rh.filter.sort.bam  \
      -j all \
      -y single  \
      -a  ../apps  \
      -c chr20  \
      -o out \
      -i  ../example/cell_cluster.csv   \
      -p  ../example/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz  \
      -r  ../example/chr20_2Mb.hg38.fa  -d 200  -t 0.1  -m 3 -s 5
```
Error:
```
FileNotFoundError: [Errno 2] could not open variant file `b'/****/out/SCvarCall/chr20.gp.vcf.gz'`: No such file or directory
```

when following the tutorial in Readme, it occurs an error as above. the output files:
```
$ ll out
total 12
drwxr-xr-x 2 jeffery A 4096 Dec 26 14:57 Bam
drwxr-xr-x 2 jeffery A 4096 Dec 26 14:57 Scriptchr20
drwxr-xr-x 2 jeffery A 4096 Dec 26 14:57 SCvarCall
$ ll out/Bam/
total 22926
-rw-r--r-- 1 jeffery A 23469221 Dec 26 14:57 chr20.filter.bam
-rw-r--r-- 1 jeffery A     6936 Dec 26 14:57 chr20.filter.bam.bai
$ ll out/Scriptchr20/
total 0
-rw-r--r-- 1 jeffery A 0 Dec 26 14:57 runBeagle.sh
$ ll out/SCvarCall/
total 0
```

How can i fix this problem?

**Comment by jinzhuangdou** [comment]
Hi,

Could you post more error/log information so that I can know which part failed? Thank you

**Comment by jefferyUstc** [comment]
Here are the logs:
```

[2022-12-26 14:57:44,351] INFO     Monopogen.py Preparing varint calling pipeline...
[2022-12-26 14:57:44,352] INFO     Monopogen.py Parameters in effect:
[2022-12-26 14:57:44,352] INFO     Monopogen.py --subcommand = [SCvarCall]
[2022-12-26 14:57:44,352] INFO     Monopogen.py --bamFile = [/home/Test/Monopogen/example/chr20_2Mb.rh.filter.sort.bam]
[2022-12-26 14:57:44,352] INFO     Monopogen.py --step = [all]
[2022-12-26 14:57:44,353] INFO     Monopogen.py --mode = [single]
[2022-12-26 14:57:44,353] INFO     Monopogen.py --chr = [chr20]
[2022-12-26 14:57:44,353] INFO     Monopogen.py --out = [/home/Test/Monopogen/test/out]
[2022-12-26 14:57:44,353] INFO     Monopogen.py --reference = [../example/chr20_2Mb.hg38.fa]
[2022-12-26 14:57:44,354] INFO     Monopogen.py --imputation_panel = [../example/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz]
[2022-12-26 14:57:44,354] INFO     Monopogen.py --depth_filter = [200]
[2022-12-26 14:57:44,354] INFO     Monopogen.py --depth_filter_monovar = [50]
[2022-12-26 14:57:44,354] INFO     Monopogen.py --alt_ratio = [0.1]
[2022-12-26 14:57:44,354] INFO     Monopogen.py --wildCluster = [2]
[2022-12-26 14:57:44,355] INFO     Monopogen.py --mutationCluster = [1]
[2022-12-26 14:57:44,355] INFO     Monopogen.py --max_mismatch = [3]
[2022-12-26 14:57:44,355] INFO     Monopogen.py --max_softClipped = [5]
[2022-12-26 14:57:44,355] INFO     Monopogen.py --app_path = [../apps]
[2022-12-26 14:57:44,356] INFO     Monopogen.py --cell_cluster = [../example/cell_cluster.csv]
[2022-12-26 14:57:44,356] INFO     Monopogen.py --logfile = [out_chr20.log]
[2022-12-26 14:57:44,356] INFO     Monopogen.py --samtools = [/home/Test/Monopogen/apps/samtools]
[2022-12-26 14:57:44,356] INFO     Monopogen.py --bcftools = [/home/Test/Monopogen/apps/bcftools]
[2022-12-26 14:57:44,356] INFO     Monopogen.py --bgzip = [/home/Test/Monopogen/apps/bgzip]
[2022-12-26 14:57:44,357] INFO     Monopogen.py --java = [java]
[2022-12-26 14:57:44,357] INFO     Monopogen.py --beagle = [/home/Test/Monopogen/apps/beagle.27Jul16.86a.jar]
[2022-12-26 14:57:44,357] INFO     Monopogen.py Checking existence of essenstial resource files...
[2022-12-26 14:57:44,359] INFO     Monopogen.py Checking dependencies...
[2022-12-26 14:57:44,477] INFO     Monopogen.py Filtering bam files...
[2022-12-26 14:57:50,577] INFO     Monopogen.py Performing Variant Calling...
[2022-12-26 14:57:50,603] INFO     Monopogen.py Generating variant statistical information ...
[E::hts_open_format] Failed to open file "/home/Test/Monopogen/test/out/SCvarCall/chr20.gp.vcf.gz" : No such file or directory
Traceback (most recent call last):
  File "/home/Test/Monopogen/test/../src/Monopogen.py", line 519, in <module>
    main()
  File "/home/Test/Monopogen/test/../src/Monopogen.py", line 514, in main
    args.func(args)
  File "/home/Test/Monopogen/test/../src/Monopogen.py", line 398, in SCvarCall
    getDPinfo(args)
  File "/home/Test/Monopogen/test/../src/Monopogen.py", line 152, in getDPinfo
    gp_vcf_in = VariantFile(out + "/SCvarCall/" +  args.chr + ".gp.vcf.gz") 
  File "pysam/libcbcf.pyx", line 4119, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4344, in pysam.libcbcf.VariantFile.open
FileNotFoundError: [Errno 2] could not open variant file `b'/home/Test/Monopogen/test/out/SCvarCall/chr20.gp.vcf.gz'`: No such file or directory
```

**Comment by jinzhuangdou** [comment]
Could you try the update version? I fix one bug on detecting job step.

**Comment by planxin** [comment]
> Could you try the update version? I fix one bug on detecting job step.

Hi, I try the update version launched on Jan 5th, but the problem still exists. Could you please help me fix this?

**Comment by thomasjay3** [comment]
I am having the same issue, and I have the most recent version. I was wondering if there are any suggestions for resolving this? Thanks!

**Comment by planxin** [comment]
> 

my solution is to add this at the top of your script :
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/xx/apps

**Comment by planxin** [comment]
> I am having the same issue, and I have the most recent version. I was wondering if there are any suggestions for resolving this? Thanks!

my solution is to add this at the top of your script :
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/xx/apps
