### ISSUE TITLE
Error in Germline 

### ISSUE THREAD

**Issue by parth2608** [KChen-lab/Monopogen#31]
Hi, I am trying to run Germline on the example provided in the repository. After successfully running preProcess, I run the following command: 

python src/Monopogen.py germline -a apps/ -t 1 -r test/region.lst -p example/ -g example/chr20_2Mb.hg38.fa -s all -o out

But I get errors and the following is the output:

[2024-01-09 11:42:35,227] INFO     Monopogen.py Performing germline variant calling...
[2024-01-09 11:42:35,227] INFO     germline.py Parameters in effect:
[2024-01-09 11:42:35,227] INFO     germline.py --subcommand = [germline]
[2024-01-09 11:42:35,227] INFO     germline.py --region = [test/region.lst]
[2024-01-09 11:42:35,227] INFO     germline.py --step = [all]
[2024-01-09 11:42:35,227] INFO     germline.py --out = [out]
[2024-01-09 11:42:35,227] INFO     germline.py --reference = [example/chr20_2Mb.hg38.fa]
[2024-01-09 11:42:35,228] INFO     germline.py --imputation_panel = [example/]
[2024-01-09 11:42:35,228] INFO     germline.py --max_softClipped = [1]
[2024-01-09 11:42:35,228] INFO     germline.py --app_path = [apps/]
[2024-01-09 11:42:35,228] INFO     germline.py --nthreads = [1]
[2024-01-09 11:42:35,228] INFO     germline.py --norun = [FALSE]
[2024-01-09 11:42:35,228] INFO     Monopogen.py Checking existence of essenstial resource files...
[2024-01-09 11:42:35,236] INFO     Monopogen.py Checking dependencies...
['bash out/Script/runGermline_chr20.sh']
/rsrch5/home/tdccct/ppshah/shared/pipelines/Monopogen/apps/bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
/rsrch5/home/tdccct/ppshah/shared/pipelines/Monopogen/apps/bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[mpileup] 2 samples in 2 input files
(mpileup) Max depth is above 1M. Potential memory hog!
beagle.27Jul16.86a.jar (version 4.1)
Copyright (C) 2014-2015 Brian L. Browning
Enter "java -jar beagle.27Jul16.86a.jar" for a summary of command line arguments.
Start time: 11:44 AM CST on 09 Jan 2024

Command line: java -Xmx20480m -jar beagle.jar
  gl=out/germline/chr20.gl.vcf.gz
  ref=example/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz
  chrom=chr20
  out=out/germline/chr20.gp
  impute=false
  modelscale=2
  nthreads=24
  gprobs=true
  niterations=0

No genetic map is specified: using 1 cM = 1 Mb
Exception in thread "main" java.lang.IllegalArgumentException: Missing line (#CHROM ...) after meta-information lines
File source: out/germline/chr20.gl.vcf.gz
null
	at vcf.VcfHeader.checkHeaderLine(VcfHeader.java:135)
	at vcf.VcfHeader.<init>(VcfHeader.java:119)
	at vcf.VcfIt.<init>(VcfIt.java:190)
	at vcf.VcfIt.create(VcfIt.java:175)
	at vcf.VcfIt.create(VcfIt.java:150)
	at main.Main.allData(Main.java:303)
	at main.Main.main(Main.java:111)
gzip: out/germline/chr20.gp.vcf.gz: No such file or directory
out/germline/chr20.gp.vcf.gz: No such file or directory
beagle.27Jul16.86a.jar (version 4.1)
Copyright (C) 2014-2015 Brian L. Browning
Enter "java -jar beagle.27Jul16.86a.jar" for a summary of command line arguments.
Start time: 11:44 AM CST on 09 Jan 2024

Command line: java -Xmx20480m -jar beagle.jar
  gt=out/germline/chr20.germline.vcf
  ref=example/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz
  chrom=chr20
  out=out/germline/chr20.phased
  impute=false
  modelscale=2
  nthreads=24
  gprobs=true
  niterations=0

No genetic map is specified: using 1 cM = 1 Mb
Exception in thread "main" java.lang.IllegalArgumentException: Missing line (#CHROM ...) after meta-information lines
File source: out/germline/chr20.germline.vcf
null
	at vcf.VcfHeader.checkHeaderLine(VcfHeader.java:135)
	at vcf.VcfHeader.<init>(VcfHeader.java:119)
	at vcf.VcfIt.<init>(VcfIt.java:190)
	at vcf.VcfIt.create(VcfIt.java:175)
	at vcf.VcfIt.create(VcfIt.java:150)
	at main.Main.allData(Main.java:297)
	at main.Main.main(Main.java:111)
[2024-01-09 11:44:08,145] INFO     Monopogen.py Success! See instructions above.

Any guidance to resolve this would be helpful. I am working on HPC system.

Thank you!

**Comment by jinzhuangdou** [comment]
Hi the error shows "/rsrch5/home/tdccct/ppshah/shared/pipelines/Monopogen/apps/bcftools: error while loading shared libraries: ". Could you try to see whether it works (as mentioned in FAQs)?

`bcftools: error while loading shared libraries: libbz2.so.1.0: not able to open shared object file: No such file or directly
Adding the apps folder of Monopogen in your library environment
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/xx/apps`

**Comment by parth2608** [comment]
I did that, but I still get the following error

/rsrch5/home/tdccct/ppshah/shared/pipelines/Monopogen/apps/bcftools/rsrch5/home/tdccct/ppshah/shared/pipelines/Monopogen/apps/bcftools: : symbol lookup errorsymbol lookup error: : /lib64/libk5crypto.so.3/lib64/libk5crypto.so.3: : undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1bundefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b

**Comment by jinzhuangdou** [comment]
Are you able to compile bcftools at your end? The version required are 
`samtools Version: 1.2 (using htslib 1.2.1)
bcftools Version: 1.8 (using htslib 1.8)
beagle.27Jul16.86a.jar (version 4.1)
tabix Version: 1.9
bgzip Version: 1.9`

**Comment by Coaxecva** [comment]
Hi @jinzhuangdou,

I successfully ran preprocess, but when I run Monopogen `germline`, I added all autosome 1-22 (even with 1 chr22), I got warnings, and it seems the process took forever to process:

python Monopogen/src/Monopogen.py  germline  -a Monopogen/apps  -r region.lst -p ./  -t 22 -g  Homo_sapiens_assembly38.fasta  -m 3 -s all  -o out_SC399_9

>     CPU time :                                   86062.00 sec.
>     Max Memory :                                 7 GB
>     Average Memory :                             5.07 GB
>     Total Requested Memory :                     30.00 GB
>     Delta Memory :                               23.00 GB

> [2024-11-12 16:08:10,587] INFO     Monopogen.py Performing germline variant calling...
[2024-11-12 16:08:10,587] INFO     germline.py Parameters in effect:
[2024-11-12 16:08:10,587] INFO     germline.py --subcommand = [germline]
[2024-11-12 16:08:10,588] INFO     germline.py --region = [region.lst]
[2024-11-12 16:08:10,588] INFO     germline.py --step = [all]
[2024-11-12 16:08:10,588] INFO     germline.py --out = [out_SC399_9]
[2024-11-12 16:08:10,588] INFO     germline.py --reference = [Homo_sapiens_assembly38.fasta]
[2024-11-12 16:08:10,588] INFO     germline.py --imputation_panel = [./]
[2024-11-12 16:08:10,588] INFO     germline.py --max_softClipped = [3]
[2024-11-12 16:08:10,588] INFO     germline.py --app_path = [Monopogen/apps]
[2024-11-12 16:08:10,588] INFO     germline.py --nthreads = [22]
[2024-11-12 16:08:10,588] INFO     germline.py --norun = [FALSE]
[2024-11-12 16:08:10,588] INFO     Monopogen.py Checking existence of essenstial resource files...
[2024-11-12 16:08:10,614] INFO     Monopogen.py Checking dependencies...
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
[mpileup] 1 samples in 1 input files
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
(mpileup) Max depth is above 1M. Potential memory hog!
Lines   total/split/realigned/skipped:  36550225/124788/11454/0

**Comment by theheking** [comment]
I have the same error, but unable to compile due to the --app_path required flag, conflict of installations. 

> Are you able to compile bcftools at your end? The version required are `samtools Version: 1.2 (using htslib 1.2.1) bcftools Version: 1.8 (using htslib 1.8) beagle.27Jul16.86a.jar (version 4.1) tabix Version: 1.9 bgzip Version: 1.9`.

**Comment by katestan** [comment]
I am also getting the error /camp/home/stanlek/home/users/stanlek/Monopogen/apps/bcftools: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b

You can hardcode a path to your own compiled version of bcftools within Monopogen.py to get around the -app_path required flag, conflict of installations issue @theheking
