### ISSUE TITLE
chr20.gp.vcf.gz: No such file or directory

### ISSUE THREAD

**Issue by dipingxian431** [KChen-lab/Monopogen#50]
Hi, I am running Germline, after successfully running preProcess.
I met a few problems. 
First, when I ran germline, the output showed that I didn't have Java. So, I installed Java using `conda install bioconda::java-jdk `. After that, I rerun it. the output showed that no bam.bai file. So, I used the `samtools index` to add the bai file. Then re-run Germine with the following command. 
```
path="/home/mingchao/Linux_file/Monopogen/Monopogen"  # where Monopogen is downloaded
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${path}/apps
python  ${path}/src/Monopogen.py  germline  \
    -a   ${path}/apps -r  /data/Mingchao/dowload_data/Monopogen/Monopogen_testfile/region.lst \
    -p  /data/Mingchao/dowload_data/Monopogen/Monopogen_testfile/  \
    -g  /data/Mingchao/dowload_data/Monopogen/Monopogen_testfile/chr20_2Mb.hg38.fa   -s all  -o /data/Mingchao/dowload_data/Monopogen/Monopogen_testout
```
The job still cannot run correctly. The output file only has chr20.gl.vcf.gz and the size is 0.  But at the end of the report shows "Monopogen.py Success! See instructions above."

The Monopogen_testout files:
```
drwxrwxr-x+ 2 mingchao mingchao 4096 Apr  7 16:48 ./
drwxrwxr-x+ 5 mingchao mingchao 4096 Apr  7 13:17 ../
-rw-rw-r--+ 1 mingchao mingchao    0 Apr  7 16:48 chr20.gl.vcf.gz
-rw-rw-r--+ 1 mingchao mingchao  692 Apr  7 16:48 chr20.gp.log
-rw-rw-r--+ 1 mingchao mingchao  699 Apr  7 16:48 chr20.phased.log
```

The output report:
```
[2024-04-07 16:48:08,516] INFO     Monopogen.py Performing germline variant calling...
[2024-04-07 16:48:08,517] INFO     germline.py Parameters in effect:
[2024-04-07 16:48:08,517] INFO     germline.py --subcommand = [germline]
[2024-04-07 16:48:08,517] INFO     germline.py --region = [/data/Mingchao/dowload_data/Monopogen/Monopogen_testfile/region.lst]
[2024-04-07 16:48:08,517] INFO     germline.py --step = [all]
[2024-04-07 16:48:08,517] INFO     germline.py --out = [/data/Mingchao/dowload_data/Monopogen/Monopogen_testout]
[2024-04-07 16:48:08,517] INFO     germline.py --reference = [/data/Mingchao/dowload_data/Monopogen/Monopogen_testfile/chr20_2Mb.hg38.fa]
[2024-04-07 16:48:08,517] INFO     germline.py --imputation_panel = [/data/Mingchao/dowload_data/Monopogen/Monopogen_testfile/]
[2024-04-07 16:48:08,517] INFO     germline.py --max_softClipped = [1]
[2024-04-07 16:48:08,517] INFO     germline.py --app_path = [/home/mingchao/Linux_file/Monopogen/Monopogen/apps]
[2024-04-07 16:48:08,517] INFO     germline.py --nthreads = [1]
[2024-04-07 16:48:08,517] INFO     germline.py --norun = [FALSE]
[2024-04-07 16:48:08,517] INFO     Monopogen.py Checking existence of essenstial resource files...
[2024-04-07 16:48:08,517] INFO     Monopogen.py Checking dependencies...
/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh: line 1: /home/mingchao/Linux_file/Monopogen/Monopogen/apps/samtools: Permission denied
/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh: line 1: /home/mingchao/Linux_file/Monopogen/Monopogen/apps/bcftools: Permission denied
/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh: line 1: /home/mingchao/Linux_file/Monopogen/Monopogen/apps/bcftools: Permission denied
/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh: line 1: /home/mingchao/Linux_file/Monopogen/Monopogen/apps/bgzip: Permission denied
beagle.27Jul16.86a.jar (version 4.1)
Copyright (C) 2014-2015 Brian L. Browning
Enter "java -jar beagle.27Jul16.86a.jar" for a summary of command line arguments.
Start time: 04:48 PM EDT on 07 Apr 2024

Command line: java -Xmx18204m -jar beagle.jar
  gl=/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/germline/chr20.gl.vcf.gz
  ref=/data/Mingchao/dowload_data/Monopogen/Monopogen_testfile/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz
  chrom=chr20
  out=/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/germline/chr20.gp
  impute=false
  modelscale=2
  nthreads=24
  gprobs=true
  niterations=0

No genetic map is specified: using 1 cM = 1 Mb
java.io.EOFException
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at blbutil.InputIt.fromGzipFile(InputIt.java:214)
        at main.Main.allData(Main.java:302)
        at main.Main.main(Main.java:111)
java.io.EOFException
Error reading /data/Mingchao/dowload_data/Monopogen/Monopogen_testout/germline/chr20.gl.vcf.gz
terminating program.
gzip: /data/Mingchao/dowload_data/Monopogen/Monopogen_testout/germline/chr20.gp.vcf.gz: No such file or directory
beagle.27Jul16.86a.jar (version 4.1)
Copyright (C) 2014-2015 Brian L. Browning
Enter "java -jar beagle.27Jul16.86a.jar" for a summary of command line arguments.
Start time: 04:48 PM EDT on 07 Apr 2024

Command line: java -Xmx18204m -jar beagle.jar
  gt=/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/germline/chr20.germline.vcf
  ref=/data/Mingchao/dowload_data/Monopogen/Monopogen_testfile/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz
  chrom=chr20
  out=/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/germline/chr20.phased
  impute=false
  modelscale=2
  nthreads=24
  gprobs=true
  niterations=0

No genetic map is specified: using 1 cM = 1 Mb
Exception in thread "main" java.lang.IllegalArgumentException: Missing line (#CHROM ...) after meta-information lines
File source: /data/Mingchao/dowload_data/Monopogen/Monopogen_testout/germline/chr20.germline.vcf
/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/germline/chr20.gp.vcf.gz: No such file or directory
        at vcf.VcfHeader.checkHeaderLine(VcfHeader.java:135)
        at vcf.VcfHeader.<init>(VcfHeader.java:119)
        at vcf.VcfIt.<init>(VcfIt.java:190)
        at vcf.VcfIt.create(VcfIt.java:175)
        at vcf.VcfIt.create(VcfIt.java:150)
        at main.Main.allData(Main.java:297)
        at main.Main.main(Main.java:111)
bash /data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh
[2024-04-07 16:48:08,799] INFO     Monopogen.py Success! See instructions above.
['bash /data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh']
```

Any guidance to resolve this would be helpful. 

Thank you so much!

**Comment by jinzhuangdou** [comment]
It shows errors as following: 
`/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh: line 1: /home/mingchao/Linux_file/Monopogen/Monopogen/apps/samtools: Permission denied
/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh: line 1: /home/mingchao/Linux_file/Monopogen/Monopogen/apps/bcftools: Permission denied
/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh: line 1: /home/mingchao/Linux_file/Monopogen/Monopogen/apps/bcftools: Permission denied
/data/Mingchao/dowload_data/Monopogen/Monopogen_testout/Script/runGermline_chr20.sh: line 1: /home/mingchao/Linux_file/Monopogen/Monopogen/apps/bgzip: Permission denied`
Could you set execute permission on  /home/mingchao/Linux_file/Monopogen/Monopogen/apps/*?  For example chmod g+x

**Comment by dipingxian431** [comment]
Thank you so much for the reply!

I tried to execute the permission by using `chmod g+x /home/mingchao/Linux_file/Monopogen2/Monopogen/apps/*` 
before:
```
(Variants) mingchao@JS-Lambda-Vector:~/Linux_file/Monopogen2/Monopogen/apps$ ll
total 41076
drwxrwxr-x 2 mingchao mingchao     4096 Apr  7 22:23 ./
drwxrwxr-x 9 mingchao mingchao     4096 Apr  7 21:59 ../
-rw-rw-r-- 1 mingchao mingchao  1939857 Apr  7 21:59 bcftools
-rw-rw-r-- 1 mingchao mingchao   300906 Apr  7 21:59 beagle.08Feb22.fa4.jar
-rw-rw-r-- 1 mingchao mingchao   330554 Apr  7 21:59 beagle.27Jul16.86a.jar
-rw-rw-r-- 1 mingchao mingchao   631018 Apr  7 21:59 bgzip
-rw-rw-r-- 1 mingchao mingchao   100800 Apr  7 21:59 gzip
-rw-rw-r-- 1 mingchao mingchao    12784 Apr  7 21:59 java
-rw-rw-r-- 1 mingchao mingchao    68192 Apr  7 21:59 libbz2.so.1.0
-rw-rw-r-- 1 mingchao mingchao  3152968 Apr  7 21:59 libcrypto.so.1.0.0
-rw-rw-r-- 1 mingchao mingchao    64528 Apr  7 21:59 libdeflate.so
-rw-rw-r-- 1 mingchao mingchao 17389398 Apr  7 21:59 picard.jar
-rw-rw-r-- 1 mingchao mingchao  2911966 Apr  7 21:59 samtools
-rw-rw-r-- 1 mingchao mingchao   683232 Apr  7 21:59 tabix
-rw-rw-r-- 1 mingchao mingchao 14444639 Apr  7 21:59 vcftools
```

After:
```
(Variants) mingchao@JS-Lambda-Vector:~/Linux_file/Monopogen2/Monopogen/apps$ ll
total 41076
drwxrwxr-x 2 mingchao mingchao     4096 Apr  7 22:23 ./
drwxrwxr-x 9 mingchao mingchao     4096 Apr  7 21:59 ../
-rw-rwxr-- 1 mingchao mingchao  1939857 Apr  7 21:59 bcftools*
-rw-rwxr-- 1 mingchao mingchao   300906 Apr  7 21:59 beagle.08Feb22.fa4.jar*
-rw-rwxr-- 1 mingchao mingchao   330554 Apr  7 21:59 beagle.27Jul16.86a.jar*
-rw-rwxr-- 1 mingchao mingchao   631018 Apr  7 21:59 bgzip*
-rw-rwxr-- 1 mingchao mingchao   100800 Apr  7 21:59 gzip*
-rw-rwxr-- 1 mingchao mingchao    12784 Apr  7 21:59 java*
-rw-rwxr-- 1 mingchao mingchao    68192 Apr  7 21:59 libbz2.so.1.0*
-rw-rwxr-- 1 mingchao mingchao  3152968 Apr  7 21:59 libcrypto.so.1.0.0*
-rw-rwxr-- 1 mingchao mingchao    64528 Apr  7 21:59 libdeflate.so*
-rw-rwxr-- 1 mingchao mingchao 17389398 Apr  7 21:59 picard.jar*
-rw-rwxr-- 1 mingchao mingchao  2911966 Apr  7 21:59 samtools*
-rw-rwxr-- 1 mingchao mingchao   683232 Apr  7 21:59 tabix*
-rw-rwxr-- 1 mingchao mingchao 14444639 Apr  7 21:59 vcftools*
```

I also test them by using  `/home/mingchao/Linux_file/Monopogen2/Monopogen/apps/samtools` the output still permission denied:`-bash: /home/mingchao/Linux_file/Monopogen2/Monopogen/apps/samtools: Permission denied`.
Same as another one: 
(Variants) mingchao@JS-Lambda-Vector:~/Linux_file/Monopogen2/Monopogen/apps$ `./gzip -h`
`-bash: ./gzip: Permission denied`

What should I do next?

Thank you so much!

**Comment by jinzhuangdou** [comment]
Could you try chmod 777 ./* to see whether it works?

**Comment by dipingxian431** [comment]
Thank you for the reply!

I tried hmod u+x ./*. But new questions come.
```
(base) mingchao@JS-Lambda-Vector:~/Linux_file/Monopogen2/Monopogen/apps$ ./bcftools 
./bcftools: error while loading shared libraries: libdeflate.so: cannot open shared object file: No such file or directory
(base) mingchao@JS-Lambda-Vector:~/Linux_file/Monopogen2/Monopogen/apps$ ./samtools
./samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```
And I can not use  `sudo apt-get install libncurses5` to install.
Do you have some other suggestions?
Thank you!

**Comment by dipingxian431** [comment]
I also test other apps. It looks like all of them cannot be right run now.
```
(base) mingchao@JS-Lambda-Vector:~/Linux_file/Monopogen2/Monopogen/apps$ ./beagle.08Feb22.fa4.jar
-bash: ./beagle.08Feb22.fa4.jar: cannot execute binary file: Exec format error
(base) mingchao@JS-Lambda-Vector:~/Linux_file/Monopogen2/Monopogen/apps$ ./bgzip 
./bgzip: error while loading shared libraries: libdeflate.so: cannot open shared object file: No such file or directory
(base) mingchao@JS-Lambda-Vector:~/Linux_file/Monopogen2/Monopogen/apps$ ./libbz2.so.1.0 
Segmentation fault (core dumped)
```
