### ISSUE TITLE
use example data but have no SNV, how should I do

### ISSUE THREAD

**Issue by kyleYin7** [KChen-lab/Monopogen#87]
[2024-11-28 01:07:58,867] INFO     Monopogen.py Performing germline variant calling...
[2024-11-28 01:07:58,867] INFO     germline.py Parameters in effect:
[2024-11-28 01:07:58,867] INFO     germline.py --subcommand = [germline]
[2024-11-28 01:07:58,867] INFO     germline.py --region = [region.lst]
[2024-11-28 01:07:58,867] INFO     germline.py --step = [all]
[2024-11-28 01:07:58,868] INFO     germline.py --out = [retina]
[2024-11-28 01:07:58,868] INFO     germline.py --reference = [/home/yjkkyle/document/Monopogen/example/chr20_2Mb.hg38.fa]
[2024-11-28 01:07:58,868] INFO     germline.py --imputation_panel = [./ref/]
[2024-11-28 01:07:58,868] INFO     germline.py --max_softClipped = [3]
[2024-11-28 01:07:58,868] INFO     germline.py --app_path = [/home/yjkkyle/document/Monopogen/apps]
[2024-11-28 01:07:58,868] INFO     germline.py --nthreads = [1]
[2024-11-28 01:07:58,868] INFO     germline.py --norun = [FALSE]
[2024-11-28 01:07:58,868] INFO     Monopogen.py Checking existence of essenstial resource files...
[2024-11-28 01:07:58,870] INFO     Monopogen.py Checking dependencies...
['bash retina/Script/runGermline_chr20.sh']
bash retina/Script/runGermline_chr20.sh
[mpileup] 1 samples in 1 input files
(mpileup) Max depth is above 1M. Potential memory hog!
Reference allele mismatch at chr20:60002 .. REF_SEQ:'N' vs VCF:'G'
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
[E::bcf_write] Broken VCF record, the number of columns at chr20:3001075 does not match the number of samples (0 vs 1)
beagle.27Jul16.86a.jar (version 4.1)
Copyright (C) 2014-2015 Brian L. Browning
Enter "java -jar beagle.27Jul16.86a.jar" for a summary of command line arguments.
Start time: 01:13 AM UTC on 28 Nov 2024

Command line: java -Xmx18204m -jar beagle.jar
  gl=retina/germline/chr20.gl.vcf.gz
  ref=./ref/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz
  chrom=chr20
  out=retina/germline/chr20.gp
  impute=false
  modelscale=2
  nthreads=24
  gprobs=true
  niterations=0

No genetic map is specified: using 1 cM = 1 Mb
Exception in thread "main" java.lang.IllegalArgumentException: No VCF records found (data source: retina/germline/chr20.gl.vcf.gz)
Check that the chromosome identifiers are the same in each input VCF
file and in the 'chrom=' command line argument (if 'chrom=' is used).
        at vcf.VcfIt.noRecordFoundError(VcfIt.java:218)
        at vcf.VcfIt.start(VcfIt.java:204)
        at vcf.VcfIt.create(VcfIt.java:177)
        at vcf.VcfIt.create(VcfIt.java:150)
        at main.Main.allData(Main.java:303)
        at main.Main.main(Main.java:111)
gzip: retina/germline/chr20.gp.vcf.gz: No such file or directory
beagle.27Jul16.86a.jar (version 4.1)
Copyright (C) 2014-2015 Brian L. Browning
Enter "java -jar beagle.27Jul16.86a.jar" for a summary of command line arguments.
Start time: 01:13 AM UTC on 28 Nov 2024

Command line: java -Xmx18204m -jar beagle.jar
  gt=retina/germline/chr20.germline.vcf
  ref=./ref/CCDG_14151_B01_GRM_WGS_2020-08-05_chr20.filtered.shapeit2-duohmm-phased.vcf.gz
  chrom=chr20
  out=retina/germline/chr20.phased
  impute=false
  modelscale=2
  nthreads=24
  gprobs=true
  niterations=0

No genetic map is specified: using 1 cM = 1 Mb
Exception in thread "main" java.lang.IllegalArgumentException: Missing line (#CHROM ...) after meta-information lines
File source: retina/germline/chr20.germline.vcf
retina/germline/chr20.gp.vcf.gz: No such file or directory
        at vcf.VcfHeader.checkHeaderLine(VcfHeader.java:135)
        at vcf.VcfHeader.<init>(VcfHeader.java:119)
        at vcf.VcfIt.<init>(VcfIt.java:190)
        at vcf.VcfIt.create(VcfIt.java:175)
        at vcf.VcfIt.create(VcfIt.java:150)
        at main.Main.allData(Main.java:297)
        at main.Main.main(Main.java:111)
[2024-11-28 01:13:17,089] INFO     Monopogen.py Success! See instructions above.

**Comment by kyleYin7** [comment]
I solved these problem but I meet a new error. I can find these files and directory but in LDrefinement it cannot find them. python  /home/yjkkyle/Monopogen/src/Monopogen.py  somatic      -a   /home/yjkkyle/Monopogen/apps  -r  /home/yjkkyle/test2/region.lst  -t 1     -i  /home/yjkkyle/test2/out2  -l  /home/yjkkyle/test2/bone-marrow_scRNA.csv   -s LDrefinement         -g   /home/yjkkyle/test2/genome.fa
[2024-12-05 02:46:59,564] INFO     Monopogen.py Run LD refinement ...
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr9.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr9
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr11.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr11
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr13.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr13
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr20.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr20
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr7.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr7
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr15.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr15
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr5.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr5
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr12.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr12
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr16.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr16
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr3.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr3
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr18.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr18
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr6.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr6
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr21.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr21
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr1.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr1
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr4.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr4
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr22.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr22
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr2.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr2
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr19.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr19
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr14.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr14
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr17.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr17
Rscript execution error: No such file or directory
Rscript /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R  /home/yjkkyle/test2/out2/somatic/chr10.gl.filter.hc.cell.mat.gz /home/yjkkyle/test2/out2/somatic/ chr10
Rscript execution error: No such file or directory
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr9 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr11 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr13 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr20 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr7 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr15 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr5 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr12 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr16 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr3 failed!
[2024-12-05 02:47:00,446] ERROR    Monopogen.py In LDrefinement step chr18 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr6 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr21 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr1 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr4 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr22 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr2 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr19 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr14 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr17 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py In LDrefinement step chr10 failed!
[2024-12-05 02:47:00,447] ERROR    Monopogen.py Failed! See instructions above.

**Comment by kyleYin7** [comment]
(SNP) yjkkyle@ss4:~/test2$ ls /home/yjkkyle/Monopogen/apps/../src/LDrefinement.R 
/home/yjkkyle/Monopogen/apps/../src/LDrefinement.R
(SNP) yjkkyle@ss4:~/test2$ ls /home/yjkkyle/test2/out2/somatic/chr10.gl.filter.hc.cell.mat.gz
/home/yjkkyle/test2/out2/somatic/chr10.gl.filter.hc.cell.mat.gz
