### ISSUE TITLE
error in Somatic SNV calling from scRNA-seq

### ISSUE THREAD

**Issue by wanghf810501** [KChen-lab/Monopogen#99]
Hi, 
I am running the example script (runSomatic.sh) in the test folder and encounter error when I run "python  ${path}/src/Monopogen.py  somatic  \
    -a   ${path}/apps  -r  ${path}/test/region.lst  -t 22 \
    -i somatic  -l test.csv  -s featureInfo    \
    -g  example/chr20_2Mb.hg38.fa   
" , and the error messages  are as following:
  from pandas.core import (
Traceback (most recent call last):
  File "/home/wanghf/Apps/Monopogen//src/Monopogen.py", line 340, in <module>
    main()
  File "/home/wanghf/Apps/Monopogen//src/Monopogen.py", line 333, in main
    args.func(args)
  File "/home/wanghf/Apps/Monopogen//src/Monopogen.py", line 136, in somatic
    validate_user_setting_somatic(args)
  File "/home/wanghf/Apps/Monopogen/src/somatic.py", line 66, in validate_user_setting_somatic
    assert os.path.isfile(phased_vcf), "The *.phased.vcf.gz file {} cannot be found! Please run germline module".format(phased_vcf)
AssertionError: The *.phased.vcf.gz file somatic/germline/chr20.phased.vcf.gz cannot be found! Please run germline module

**Comment by wanghf810501** [comment]
I found that that is because there is something wrong with the former step.
